build_from:
  armv7: homeassistant/armv7-base-debian:buster
  aarch64: homeassistant/aarch64-base-debain:buster
  amd64: homeassistant/amd64-base-debian:buster
  i386: homeassistant/i386-base-debian:buster